model:
  denoiser:
    bridge_type: 'vp'
    feature_size: 7
    beta_d: 2
    beta_min: 0.1
    sigma_data: 0.5
    sigma_max: 1
    sigma_min: 0.0001
    schedule_sampler: 'real-uniform'
    use_ema: true
    ema_decay: 0.999
    weight_decay: 0.0
    weight_schedule: 'vp_bridge'
    loss_x_weight: 100

  backbone: 
    type: 'EGNN'

training:
  batch_size: 100
  log_interval: 100
  save_interval: 1000
  test_interval: 1000
  total_training_steps: 10000000
  learning_rate: 0.0001
  lr_anneal_steps: 0
